/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import caex.caex30.caex.Attribute;

/**
 * A sample validator interface for {@link caex.caex30.caex.AttributeNameMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeNameMappingValidator {
	boolean validate();

	boolean validateRoleAttributeName(String value);
	boolean validateSystemUnitAttributeName(String value);
	boolean validateRoleAttribute(Attribute value);
	boolean validateSystemUnitAttribute(Attribute value);
}
