/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import caex.caex30.caex.Attribute;
import caex.caex30.caex.AttributeValueRequirement;
import caex.caex30.caex.RefSemantic;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link caex.caex30.caex.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateDefaultValue(String value);
	boolean validateValue(String value);
	boolean validateRefSemantic(EList<RefSemantic> value);
	boolean validateConstraint(EList<AttributeValueRequirement> value);
	boolean validateAttribute(EList<Attribute> value);
	boolean validateAttributeDataType(String value);
	boolean validateRefAttributeType(String value);
	boolean validateUnit(String value);
	boolean validateReferenceAttribute(Attribute value);
}
