/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import caex.caex30.caex.AdditionalInformation;
import caex.caex30.caex.ChangeMode;
import caex.caex30.caex.Copyright;
import caex.caex30.caex.Description;
import caex.caex30.caex.Revision;
import caex.caex30.caex.Version;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link caex.caex30.caex.CAEXBasicObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CAEXBasicObjectValidator {
	boolean validate();

	boolean validateChangeMode(ChangeMode value);
	boolean validateDescription(Description value);
	boolean validateVersion(Version value);
	boolean validateRevision(EList<Revision> value);
	boolean validateCopyright(Copyright value);
	boolean validateAdditionalInformation(EList<AdditionalInformation> value);
}
