/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import caex.caex30.caex.ExternalInterface;

/**
 * A sample validator interface for {@link caex.caex30.caex.InterfaceIDMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterfaceIDMappingValidator {
	boolean validate();

	boolean validateRoleInterfaceID(String value);
	boolean validateSystemUnitInterfaceID(String value);
	boolean validateRoleInterface(ExternalInterface value);
	boolean validateSystemUnitInterface(ExternalInterface value);
}
