/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import caex.caex30.caex.RoleRequirements;
import caex.caex30.caex.SystemUnitClass;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link caex.caex30.caex.InternalElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InternalElementValidator {
	boolean validate();

	boolean validateRoleRequirements(EList<RoleRequirements> value);
	boolean validateRefBaseSystemUnitPath(String value);
	boolean validateBaseSystemUnit(SystemUnitClass value);
}
