/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import caex.caex30.caex.Attribute;
import caex.caex30.caex.InterfaceClass;
import caex.caex30.caex.Mapping;
import caex.caex30.caex.RoleClass;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link caex.caex30.caex.RoleRequirements}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoleRequirementsValidator {
	boolean validate();

	boolean validateAttribute(EList<Attribute> value);
	boolean validateExternalInterface(EList<InterfaceClass> value);
	boolean validateMappingObject(Mapping value);
	boolean validateRoleClass(RoleClass value);
	boolean validateRefBaseRoleClassPath(String value);
	boolean validateName(String value);
}
