/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * A sample validator interface for {@link caex.caex30.caex.SourceDocumentInformation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SourceDocumentInformationValidator {
	boolean validate();

	boolean validateLastWritingDateTime(XMLGregorianCalendar value);
	boolean validateOriginID(String value);
	boolean validateOriginName(String value);
	boolean validateOriginProjectID(String value);
	boolean validateOriginProjectTitle(String value);
	boolean validateOriginRelease(String value);
	boolean validateOriginVendor(String value);
	boolean validateOriginVendorURL(String value);
	boolean validateOriginVersion(String value);
}
