/**
 *
 * $Id$
 */
package caex.caex30.caex.validation;

import caex.caex30.caex.Attribute;
import caex.caex30.caex.InterfaceClass;
import caex.caex30.caex.InternalElement;
import caex.caex30.caex.InternalLink;
import caex.caex30.caex.SupportedRoleClass;
import caex.caex30.caex.SystemUnitClass;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link caex.caex30.caex.SystemUnitClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemUnitClassValidator {
	boolean validate();

	boolean validateAttribute(EList<Attribute> value);
	boolean validateExternalInterface(EList<InterfaceClass> value);
	boolean validateInternalElement(EList<InternalElement> value);
	boolean validateSupportedRoleClass(EList<SupportedRoleClass> value);
	boolean validateInternalLink(EList<InternalLink> value);
	boolean validateBaseClass(SystemUnitClass value);
	boolean validateSystemUnitClass(EList<SystemUnitClass> value);
	boolean validateRefBaseClassPath(String value);
}
